- project:
    templates:
      - check-requirements
      - horizon-non-primary-django-jobs
      - horizon-nodejs-jobs
      - openstack-python3-zed-jobs-horizon
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
