- project:
    templates:
      - check-requirements
      - horizon-non-primary-django-jobs
      - horizon-nodejs10-jobs
      - openstack-lower-constraints-jobs-horizon
      - openstack-python-jobs-horizon
      - openstack-python3-train-jobs-horizon
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - openstack-tox-py36:
            voting: false
            required-projects:
              - openstack/horizon
